apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helpers.fullname" . }}
  labels:
    {{- include "helpers.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helpers.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helpers.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helpers.serviceAccountName" . }}
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: main
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
          {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command: ["python3"]
          args:
            - "-m"
            - "sglang.launch_server"
          {{- with .Values.extraArgs }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- $limits := default dict .Values.resources.limits }}
            {{- if .Values.gpu.enabled }}
          # If gpu is enabled, it can either be a NVIDIA card or a AMD card
              {{- if or (eq .Values.gpu.type "nvidia") (not .Values.gpu.type) }}
          # NVIDIA is assumed by default if no value is set and GPU is enabled
          # NVIDIA cards can have mig enabled (i.e., the card is sliced into parts
          # Therefore, the first case is no migs enabled
                {{- if or (not .Values.gpu.mig) (not .Values.gpu.mig.enabled ) }}
                  {{- $gpuLimit := dict (.Values.gpu.nvidiaResource | default "nvidia.com/gpu") (.Values.gpu.number | default 1) }}
                  {{- $limits = merge $limits $gpuLimit }}
          # Second case is mig is enabled
                {{- else if or (.Values.gpu.mig.enabled) }}
          # Initialize empty dictionary
                  {{- $migDevices := dict -}}
          # Loop over the entries in the mig devices
                  {{- range $key, $value := .Values.gpu.mig.devices }}
                    {{- $migKey := printf "nvidia.com/mig-%s" $key -}}
                    {{- $migDevices = merge $migDevices (dict $migKey $value) -}}
                  {{- end }}
                  {{- $limits = merge $limits $migDevices}}
                {{- end }}
              {{- end }}
              {{- if eq .Values.gpu.type "amd" }}
                {{- $gpuLimit := dict "amd.com/gpu" (.Values.gpu.number | default 1) }}
                {{- $limits = merge $limits $gpuLimit }}
              {{- end }}
            {{- end }}
            {{- $ressources := deepCopy (dict "limits" $limits) | mergeOverwrite .Values.resources }}
            {{- toYaml $ressources | nindent 12 }}
          {{- end}}
          {{- if .Values.livenessProbeEnabled }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end}}
          {{- if .Values.readinessProbeEnabled }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end}}
          {{- with .Values.lifecycle}}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end}}
          volumeMounts:
            - name: shm
              mountPath: /dev/shm
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: data
              mountPath: /root/.cache/huggingface
              subPath: hf_cache
            - name: data
              mountPath: /root/.cache/modelscope
              subPath: ms_cache
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 10Gi
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "helpers.name" . }}-pvc
        {{- else }}
        - name: data
          emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.gpu.enabled .Values.tolerations }}
      tolerations:
        {{- if and .Values.gpu.enabled (and 
              ( or (eq .Values.gpu.type "nvidia") (not .Values.gpu.type)) 
              ( or (not .Values.gpu.mig) (not .Values.gpu.mig.enabled))
            ) }}
        - key: '{{ (.Values.gpu.nvidiaResource | default "nvidia.com/gpu") }}'
          operator: Exists
          effect: NoSchedule
          {{- else if and .Values.gpu.enabled (and 
              ( or (eq .Values.gpu.type "nvidia") (not .Values.gpu.type)) 
              (( .Values.gpu.mig.enabled))
            ) }}
            {{- range $key, $value := .Values.gpu.mig.devices }}
        - key: nvidia.com/mig-{{ $key }}
          operator: Exists
          effect: NoSchedule
            {{- end }}
        {{- end }}
        {{- with .Values.tolerations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
