annotations:
  group: fun.freechat
autoscaling:
  enabled: false
cert:
  manager:
    namespace: cert-manager
    version: v1.16.1
gpu:
  enabled: true
  type: 'nvidia'
  number: 1
image:
  repository: lmsysorg/sglang
  tag: latest
ingress:
  enabled: false
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: freechat-sgl-letsencrypt-http01
  hosts:
    - host: sgl.freechat.fun
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: false
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  annotations:
    helm.sh/resource-policy: keep
  size: 120Gi
  storageClass: default
pdb:
  create: true
  minAvailable: ''
  maxUnavailable: ''
replicaCount: 1
livenessProbeEnabled: true
livenessProbe:
  httpGet:
    path: /health
    port: 30000
  initialDelaySeconds: 120
  periodSeconds: 15
  timeoutSeconds: 10
  failureThreshold: 3
readinessProbeEnabled: false
readinessProbe:
  httpGet:
    path: /health_generate
    port: 30000
  initialDelaySeconds: 120
  periodSeconds: 15
  timeoutSeconds: 10
  failureThreshold: 3
  successThreshold: 1
resources:
  requests: {}
  limits: {}
service:
  enabled: true
  port: 30000
  type: ClusterIP
serviceAccount:
  create: true
  automount: false
